version: '3.7'

volumes:
  webapp:

networks:
  app-network:

services:

  nginx:
    image: nginx:1.17.5-alpine
    container_name: nginx
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'
    depends_on:
      - webapp
      # - restapi
    networks:
      - app-network

  # restapi:
  #   ports:
  #     - '3001:3001'
  #   networks:
  #     - app-network

  webapp:
    restart: always
    container_name: webapp
    build:
      context: ./webapp
      target: 'build-stage'
      dockerfile: .docker/Dockerfile
    volumes:
      - webapp:/app
    networks:
      - app-network